### ISSUE TITLE
Allow cancelling of a test

### ISSUE THREAD

**Issue by SimonRichardson** [babakks/vscode-go-test-suite#17]
We're spawning new go tests, but if you've got a test that's hanging/deadlocked, then it would be nice to kill the spawned job. The workaround is to kill the parent process (vscode), which isn't ideal.

**Comment by babakks** [comment]
Thanks for the suggestion, @SimonRichardson. The new version of the extension (v0.0.15) supports the cancelling of test runs. To cancel a test, you'd need to click on the stop button next to the running test's name in the "Test Output" pane. That will kill the underlying `go test ...` process.
