### ISSUE TITLE
gocheck's basic example does not work with vscode-go-test-suite

### ISSUE THREAD

**Issue by tigarmo** [babakks/vscode-go-test-suite#20]
Hi! gocheck's "hello world" [example](http://labix.org/gocheck):

```go
package hello_test

import (
    "testing"
    "io"

    . "gopkg.in/check.v1"
)

// Hook up gocheck into the "go test" runner.
func Test(t *testing.T) { TestingT(t) }

type MySuite struct{}

var _ = Suite(&MySuite{})

func (s *MySuite) TestHelloWorld(c *C) {
    c.Assert(42, Equals, "42")
    c.Assert(io.ErrClosedPipe, ErrorMatches, "io: .*on closed pipe")
    c.Check(42, Equals, 42)
}
```

... does not show the run/debug lens on `TestHelloWorld`. I believe this is because of the "dot-import" (` . "gopkg.in/check.v1"`), because if I change the code to explicitly use the `check` package everywhere, like this:

```go
package hello_test

import (
	"io"
	"testing"

	"gopkg.in/check.v1"
)

// Hook up gocheck into the "go test" runner.
func Test(t *testing.T) { check.TestingT(t) }

type MySuite struct{}

var _ = check.Suite(&MySuite{})

func (s *MySuite) TestHelloWorld(c *check.C) {
	c.Assert(42, check.Equals, "42")
	c.Assert(io.ErrClosedPipe, check.ErrorMatches, "io: .*on closed pipe")
	c.Check(42, check.Equals, 42)
}
```

... then the lens show up as expected. Do you think it would be possible/reasonable to take import statements like ` . "gopkg.in/check.v1"` into account when parsing the test file?

**Comment by babakks** [comment]
Thanks for reporting this @tigarmo.

I just pushed a fix for this and it is now available in the new version `v0.0.16`. Please upgrade your extension and let me know if it didn't work as expected.

**Comment by tigarmo** [comment]
😮 that was super fast! I can confirm that with version 0.0.16 all my gocheck tests have the expected lens
thanks a lot!

**Comment by babakks** [comment]
Great. I'm happy to hear that. ❤️
